// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2lHhyQl5XxZhgGzio_I5Lg0fqOwGmFro',
    appId: '1:833346345845:web:1cb77f20bded4d380b913c',
    messagingSenderId: '833346345845',
    projectId: 'cooig-fa0d9',
    authDomain: 'cooig-fa0d9.firebaseapp.com',
    storageBucket: 'cooig-fa0d9.appspot.com',
    measurementId: 'G-TH33Q6VCLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9YBGXrIPD8SHRvWvLj6EoPK1rbqf377M',
    appId: '1:833346345845:android:787128b01c51c1f40b913c',
    messagingSenderId: '833346345845',
    projectId: 'cooig-fa0d9',
    storageBucket: 'cooig-fa0d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjt7-NrOUOFdOjO0c-RuP0bh__L87FBi0',
    appId: '1:833346345845:ios:1ba1c22b72e2d0f30b913c',
    messagingSenderId: '833346345845',
    projectId: 'cooig-fa0d9',
    storageBucket: 'cooig-fa0d9.appspot.com',
    androidClientId:
        '833346345845-01vetlt5odpetviv38qcq0o2j53hudgi.apps.googleusercontent.com',
    iosClientId:
        '833346345845-qfjab35249fvi454j9g5iv8801c3p3kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cooigFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjt7-NrOUOFdOjO0c-RuP0bh__L87FBi0',
    appId: '1:833346345845:ios:1ba1c22b72e2d0f30b913c',
    messagingSenderId: '833346345845',
    projectId: 'cooig-fa0d9',
    storageBucket: 'cooig-fa0d9.appspot.com',
    androidClientId:
        '833346345845-01vetlt5odpetviv38qcq0o2j53hudgi.apps.googleusercontent.com',
    iosClientId:
        '833346345845-qfjab35249fvi454j9g5iv8801c3p3kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cooigFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2lHhyQl5XxZhgGzio_I5Lg0fqOwGmFro',
    appId: '1:833346345845:web:caac2d7e64b3b85d0b913c',
    messagingSenderId: '833346345845',
    projectId: 'cooig-fa0d9',
    authDomain: 'cooig-fa0d9.firebaseapp.com',
    storageBucket: 'cooig-fa0d9.appspot.com',
    measurementId: 'G-DFRPV6RB18',
  );
}
